name: PHP Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 3. Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # 4. Build and Start Docker Containers
      - name: Build and Start Containers
        run: docker-compose up -d --build

      # 5. Run Tests (Optional)
      # Tambahkan perintah pengujian jika Anda memiliki pengujian otomatis
      # - name: Run Tests
      #   run: phpunit

      # 6. Stop and Clean up Docker Containers
      - name: Stop and Clean up Containers
        run: docker-compose down
