name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    
    # Build dan push Docker image
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push PHP Apache image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: littlemarmut23/foodapp2:php-apache-${{ github.sha }}
    
    # Deploy ke Kubernetes
    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/php-apache-deployment php-apache-container=littlemarmut23/foodapp2:php-apache-${{ github.sha }}
        kubectl rollout status deployment/php-apache-deployment