name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    # Build and test PHP application
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    
    - name: Install dependencies
      run: composer install
    
    - name: Run tests
      run: vendor/bin/phpunit
    
    # Build and push Docker image
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push PHP Apache image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: littlemarmut23/foodapp2:php-apache-${{ github.sha }}
    
    # Deploy to Kubernetes
    - name: Install kubectl
      uses: azure/setup-kubectl@v1
    
    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yml
        export KUBECONFIG=kubeconfig.yml
    
    - name: Update deployment image
      run: |
        kubectl set image deployment/php-apache-deployment php-apache-container=littlemarmut23/foodapp2:php-apache-${{ github.sha }}
        
    - name: Verify deployment
      run: |
        kubectl rollout status deployment/php-apache-deployment
